import { UNIT1, DIGITS, MATH_PROBLEMS } from './data.js';

const SFX = './assets/audio/sfx/';
const VOICE = './assets/audio/voice/';
const U2 = './assets/audio/unit2/';
const COUNT_TOTALS = ['1', '2', '3', '4', '5'];

const LETTER_SFX = [
  SFX + 'correct.mp3',
  SFX + 'stage-clear.mp3',
  SFX + 'transition-sting.mp3',
];

function letterSteps(face) {
  return [
    { id: 'hello', icon: face, tone: 'primary' },
    { id: 'whatsthis', icon: '❓', tone: 'reward' },
    { id: 'chant', icon: '🎵', tone: 'celebration' },
    { id: 'peekaboo', icon: '👀', tone: 'success' },
    { id: 'story', icon: '📖', tone: 'grape' },
    { id: 'bubbles', icon: '🫧', tone: 'primary' },
    { id: 'popup', icon: '🌟', tone: 'celebration' },
  ];
}

const WORDS_2 = [
  { word: 'duck', letter: 'D', letters: 'D d', img: './assets/units/2/words/duck.png',
    utter: './assets/units/2/audio/duck.mp3', wordAtMs: 1406, durMs: 2060 },
  { word: 'doll', letter: 'D', letters: 'D d', img: './assets/units/2/words/doll.png',
    utter: './assets/units/2/audio/doll.mp3', wordAtMs: 1296, durMs: 1920 },
  { word: 'door', letter: 'D', letters: 'D d', img: './assets/units/2/words/door.png',
    utter: './assets/units/2/audio/door.mp3', wordAtMs: 1341, durMs: 1889 },
  { word: 'egg', letter: 'E', letters: 'E e', img: './assets/units/2/words/egg.png',
    utter: './assets/units/2/audio/egg.mp3', wordAtMs: 1317, durMs: 1775 },
  { word: 'elephant', letter: 'E', letters: 'E e', img: './assets/units/2/words/elephant.png',
    utter: './assets/units/2/audio/elephant.mp3', wordAtMs: 1316, durMs: 2048 },
  { word: 'elbow', letter: 'E', letters: 'E e', img: './assets/units/2/words/elbow.png',
    utter: './assets/units/2/audio/elbow.mp3', wordAtMs: 1337, durMs: 2019 },
  { word: 'fish', letter: 'F', letters: 'F f', img: './assets/units/2/words/fish.png',
    utter: './assets/units/2/audio/fish.mp3', wordAtMs: 1337, durMs: 2006 },
  { word: 'fork', letter: 'F', letters: 'F f', img: './assets/units/2/words/fork.png',
    utter: './assets/units/2/audio/fork.mp3', wordAtMs: 1359, durMs: 2042 },
  { word: 'frog', letter: 'F', letters: 'F f', img: './assets/units/2/words/frog.png',
    utter: './assets/units/2/audio/frog.mp3', wordAtMs: 1343, durMs: 2048 },
];

const WORDS_3 = [
  { word: 'girl', letter: 'G', letters: 'G g', img: './assets/units/3/words/girl.png',
    utter: './assets/units/3/audio/girl.mp3', wordAtMs: 1555, durMs: 2210 },
  { word: 'glove', letter: 'G', letters: 'G g', img: './assets/units/3/words/glove.png',
    utter: './assets/units/3/audio/glove.mp3', wordAtMs: 1426, durMs: 2210 },
  { word: 'green', letter: 'G', letters: 'G g', img: './assets/units/3/words/green.png',
    utter: './assets/units/3/audio/green.mp3', wordAtMs: 1397, durMs: 2158 },
  { word: 'hand', letter: 'H', letters: 'H h', img: './assets/units/3/words/hand.png',
    utter: './assets/units/3/audio/hand.mp3', wordAtMs: 1600, durMs: 2418 },
  { word: 'hat', letter: 'H', letters: 'H h', img: './assets/units/3/words/hat.png',
    utter: './assets/units/3/audio/hat.mp3', wordAtMs: 1620, durMs: 2418 },
  { word: 'hippo', letter: 'H', letters: 'H h', img: './assets/units/3/words/hippo.png',
    utter: './assets/units/3/audio/hippo.mp3', wordAtMs: 1613, durMs: 2366 },
  { word: 'ink', letter: 'I', letters: 'I i', img: './assets/units/3/words/ink.png',
    utter: './assets/units/3/audio/ink.mp3', wordAtMs: 1567, durMs: 2210 },
  { word: 'igloo', letter: 'I', letters: 'I i', img: './assets/units/3/words/igloo.png',
    utter: './assets/units/3/audio/igloo.mp3', wordAtMs: 1522, durMs: 2262 },
  { word: 'Indian', letter: 'I', letters: 'I i', img: './assets/units/3/words/indian.png',
    utter: './assets/units/3/audio/indian.mp3', wordAtMs: 1521, durMs: 2314 },
];

const WORDS_4 = [
  { word: 'jet', letter: 'J', letters: 'J j', img: './assets/units/4/words/jet.png',
    utter: './assets/units/4/audio/jet.mp3', wordAtMs: 1798, durMs: 2470 },
  { word: 'jar', letter: 'J', letters: 'J j', img: './assets/units/4/words/jar.png',
    utter: './assets/units/4/audio/jar.mp3', wordAtMs: 1709, durMs: 2418 },
  { word: 'jacket', letter: 'J', letters: 'J j', img: './assets/units/4/words/jacket.png',
    utter: './assets/units/4/audio/jacket.mp3', wordAtMs: 1553, durMs: 2314 },
  { word: 'key', letter: 'K', letters: 'K k', img: './assets/units/4/words/key.png',
    utter: './assets/units/4/audio/key.mp3', wordAtMs: 1588, durMs: 2210 },
  { word: 'king', letter: 'K', letters: 'K k', img: './assets/units/4/words/king.png',
    utter: './assets/units/4/audio/king.mp3', wordAtMs: 1599, durMs: 2262 },
  { word: 'kangaroo', letter: 'K', letters: 'K k', img: './assets/units/4/words/kangaroo.png',
    utter: './assets/units/4/audio/kangaroo.mp3', wordAtMs: 1510, durMs: 2366 },
  { word: 'lion', letter: 'L', letters: 'L l', img: './assets/units/4/words/lion.png',
    utter: './assets/units/4/audio/lion.mp3', wordAtMs: 1636, durMs: 2418 },
  { word: 'lamp', letter: 'L', letters: 'L l', img: './assets/units/4/words/lamp.png',
    utter: './assets/units/4/audio/lamp.mp3', wordAtMs: 1546, durMs: 2210 },
  { word: 'lemon', letter: 'L', letters: 'L l', img: './assets/units/4/words/lemon.png',
    utter: './assets/units/4/audio/lemon.mp3', wordAtMs: 1538, durMs: 2262 },
];

const WORDS_5 = [
  { word: 'mom', letter: 'M', letters: 'M m', img: './assets/units/5/words/mom.png',
    utter: './assets/units/5/audio/mom.mp3', wordAtMs: 1678, durMs: 2366 },
  { word: 'milk', letter: 'M', letters: 'M m', img: './assets/units/5/words/milk.png',
    utter: './assets/units/5/audio/milk.mp3', wordAtMs: 1787, durMs: 2470 },
  { word: 'melon', letter: 'M', letters: 'M m', img: './assets/units/5/words/melon.png',
    utter: './assets/units/5/audio/melon.mp3', wordAtMs: 1677, durMs: 2418 },
  { word: 'nut', letter: 'N', letters: 'N n', img: './assets/units/5/words/nut.png',
    utter: './assets/units/5/audio/nut.mp3', wordAtMs: 1772, durMs: 2418 },
  { word: 'nail', letter: 'N', letters: 'N n', img: './assets/units/5/words/nail.png',
    utter: './assets/units/5/audio/nail.mp3', wordAtMs: 1712, durMs: 2470 },
  { word: 'neck', letter: 'N', letters: 'N n', img: './assets/units/5/words/neck.png',
    utter: './assets/units/5/audio/neck.mp3', wordAtMs: 1716, durMs: 2366 },
  { word: 'onion', letter: 'O', letters: 'O o', img: './assets/units/5/words/onion.png',
    utter: './assets/units/5/audio/onion.mp3', wordAtMs: 1895, durMs: 2626 },
  { word: 'ox', letter: 'O', letters: 'O o', img: './assets/units/5/words/ox.png',
    utter: './assets/units/5/audio/ox.mp3', wordAtMs: 2081, durMs: 2834 },
  { word: 'orange', letter: 'O', letters: 'O o', img: './assets/units/5/words/orange.png',
    utter: './assets/units/5/audio/orange.mp3', wordAtMs: 2076, durMs: 2834 },
];

const WORDS_6 = [
  { word: 'pig', letter: 'P', letters: 'P p', img: './assets/units/6/words/pig.png',
    utter: './assets/units/6/audio/pig.mp3', wordAtMs: 1861, durMs: 2418 },
  { word: 'pen', letter: 'P', letters: 'P p', img: './assets/units/6/words/pen.png',
    utter: './assets/units/6/audio/pen.mp3', wordAtMs: 1820, durMs: 2418 },
  { word: 'pear', letter: 'P', letters: 'P p', img: './assets/units/6/words/pear.png',
    utter: './assets/units/6/audio/pear.mp3', wordAtMs: 1863, durMs: 2470 },
  { word: 'queen', letter: 'Q', letters: 'Q q', img: './assets/units/6/words/queen.png',
    utter: './assets/units/6/audio/queen.mp3', wordAtMs: 1938, durMs: 2574 },
  { word: 'quilt', letter: 'Q', letters: 'Q q', img: './assets/units/6/words/quilt.png',
    utter: './assets/units/6/audio/quilt.mp3', wordAtMs: 1872, durMs: 2522 },
  { word: 'quiet', letter: 'Q', letters: 'Q q', img: './assets/units/6/words/quiet.png',
    utter: './assets/units/6/audio/quiet.mp3', wordAtMs: 1881, durMs: 2678 },
  { word: 'ring', letter: 'R', letters: 'R r', img: './assets/units/6/words/ring.png',
    utter: './assets/units/6/audio/ring.mp3', wordAtMs: 1931, durMs: 2626 },
  { word: 'red', letter: 'R', letters: 'R r', img: './assets/units/6/words/red.png',
    utter: './assets/units/6/audio/red.mp3', wordAtMs: 1891, durMs: 2574 },
  { word: 'rabbit', letter: 'R', letters: 'R r', img: './assets/units/6/words/rabbit.png',
    utter: './assets/units/6/audio/rabbit.mp3', wordAtMs: 1916, durMs: 2730 },
];

const WORDS_7 = [
  { word: 'sun', letter: 'S', letters: 'S s', img: './assets/units/7/words/sun.png',
    utter: './assets/units/7/audio/sun.mp3', wordAtMs: 1865, durMs: 2418 },
  { word: 'sand', letter: 'S', letters: 'S s', img: './assets/units/7/words/sand.png',
    utter: './assets/units/7/audio/sand.mp3', wordAtMs: 1917, durMs: 2678 },
  { word: 'sock', letter: 'S', letters: 'S s', img: './assets/units/7/words/sock.png',
    utter: './assets/units/7/audio/sock.mp3', wordAtMs: 1899, durMs: 2626 },
  { word: 'sea', letter: 'S', letters: 'S s', img: './assets/units/7/words/sea.png',
    utter: './assets/units/7/audio/sea.mp3', wordAtMs: 1909, durMs: 2574 },
  { word: 'tent', letter: 'T', letters: 'T t', img: './assets/units/7/words/tent.png',
    utter: './assets/units/7/audio/tent.mp3', wordAtMs: 1881, durMs: 2522 },
  { word: 'toe', letter: 'T', letters: 'T t', img: './assets/units/7/words/toe.png',
    utter: './assets/units/7/audio/toe.mp3', wordAtMs: 1894, durMs: 2522 },
  { word: 'tiger', letter: 'T', letters: 'T t', img: './assets/units/7/words/tiger.png',
    utter: './assets/units/7/audio/tiger.mp3', wordAtMs: 1916, durMs: 2678 },
  { word: 'turtle', letter: 'T', letters: 'T t', img: './assets/units/7/words/turtle.png',
    utter: './assets/units/7/audio/turtle.mp3', wordAtMs: 1936, durMs: 2626 },
];

const WORDS_8 = [
  { word: 'uncle', letter: 'U', letters: 'U u', img: './assets/units/8/words/uncle.png',
    utter: './assets/units/8/audio/uncle.mp3', wordAtMs: 1915, durMs: 2574 },
  { word: 'under', letter: 'U', letters: 'U u', img: './assets/units/8/words/under.png',
    utter: './assets/units/8/audio/under.mp3', wordAtMs: 2036, durMs: 2730 },
  { word: 'umbrella', letter: 'U', letters: 'U u', img: './assets/units/8/words/umbrella.png',
    utter: './assets/units/8/audio/umbrella.mp3', wordAtMs: 1983, durMs: 2782 },
  { word: 'van', letter: 'V', letters: 'V v', img: './assets/units/8/words/van.png',
    utter: './assets/units/8/audio/van.mp3', wordAtMs: 2032, durMs: 2782 },
  { word: 'vest', letter: 'V', letters: 'V v', img: './assets/units/8/words/vest.png',
    utter: './assets/units/8/audio/vest.mp3', wordAtMs: 2029, durMs: 2782 },
  { word: 'violin', letter: 'V', letters: 'V v', img: './assets/units/8/words/violin.png',
    utter: './assets/units/8/audio/violin.mp3', wordAtMs: 1970, durMs: 2938 },
  { word: 'watch', letter: 'W', letters: 'W w', img: './assets/units/8/words/watch.png',
    utter: './assets/units/8/audio/watch.mp3', wordAtMs: 2102, durMs: 2886 },
  { word: 'wand', letter: 'W', letters: 'W w', img: './assets/units/8/words/wand.png',
    utter: './assets/units/8/audio/wand.mp3', wordAtMs: 1972, durMs: 2730 },
  { word: 'window', letter: 'W', letters: 'W w', img: './assets/units/8/words/window.png',
    utter: './assets/units/8/audio/window.mp3', wordAtMs: 1944, durMs: 2730 },
];

const WORDS_9 = [
  { word: 'ax', letter: 'X', letters: 'X x', img: './assets/units/9/words/ax.png',
    utter: './assets/units/9/audio/ax.mp3', wordAtMs: 2113, durMs: 2782 },
  { word: 'fox', letter: 'X', letters: 'X x', img: './assets/units/9/words/fox.png',
    utter: './assets/units/9/audio/fox.mp3', wordAtMs: 1826, durMs: 2574 },
  { word: 'X-ray', letter: 'X', letters: 'X x', img: './assets/units/9/words/x-ray.png',
    utter: './assets/units/9/audio/x-ray.mp3', wordAtMs: 1854, durMs: 2678 },
  { word: 'yak', letter: 'Y', letters: 'Y y', img: './assets/units/9/words/yak.png',
    utter: './assets/units/9/audio/yak.mp3', wordAtMs: 1972, durMs: 2626 },
  { word: 'yellow', letter: 'Y', letters: 'Y y', img: './assets/units/9/words/yellow.png',
    utter: './assets/units/9/audio/yellow.mp3', wordAtMs: 1896, durMs: 2574 },
  { word: 'yo-yo', letter: 'Y', letters: 'Y y', img: './assets/units/9/words/yo-yo.png',
    utter: './assets/units/9/audio/yo-yo.mp3', wordAtMs: 1908, durMs: 2678 },
  { word: 'zebra', letter: 'Z', letters: 'Z z', img: './assets/units/9/words/zebra.png',
    utter: './assets/units/9/audio/zebra.mp3', wordAtMs: 2017, durMs: 2782 },
  { word: 'zero', letter: 'Z', letters: 'Z z', img: './assets/units/9/words/zero.png',
    utter: './assets/units/9/audio/zero.mp3', wordAtMs: 1962, durMs: 2782 },
  { word: 'zipper', letter: 'Z', letters: 'Z z', img: './assets/units/9/words/zipper.png',
    utter: './assets/units/9/audio/zipper.mp3', wordAtMs: 1955, durMs: 2678 },
];

const CHANT_1 = {
  audio: './assets/audio/chant.mp3',
  duration: 55.875,
  cues: [
    { word: 'ant', letter: 'A', letters: 'A a', img: './assets/images/ant.png',
      t: 9.083, beat: 8.25, echoStart: 10.11, echoEnd: 11.48 },
    { word: 'apple', letter: 'A', letters: 'A a', img: './assets/images/apple.png',
      t: 12.917, beat: 12.05, echoStart: 13.94, echoEnd: 15.48 },
    { word: 'alligator', letter: 'A', letters: 'A a', img: './assets/images/alligator.png',
      t: 16.708, beat: 15.85, echoStart: 17.608, echoEnd: 19.808 },
    { word: 'ball', letter: 'B', letters: 'B b', img: './assets/images/ball.png',
      t: 24.292, beat: 23.42, echoStart: 25.22, echoEnd: 26.85 },
    { word: 'bear', letter: 'B', letters: 'B b', img: './assets/images/bear.png',
      t: 28.083, beat: 27.17, echoStart: 29.04, echoEnd: 30.58 },
    { word: 'bag', letter: 'B', letters: 'B b', img: './assets/images/bag.png',
      t: 31.917, beat: 30.94, echoStart: 32.91, echoEnd: 34.38 },
    { word: 'cup', letter: 'C', letters: 'C c', img: './assets/images/cup.png',
      t: 39.5, beat: 38.75, echoStart: 40.63, echoEnd: 42 },
    { word: 'cow', letter: 'C', letters: 'C c', img: './assets/images/cow.png',
      t: 43.292, beat: 42.48, echoStart: 44.38, echoEnd: 45.77 },
    { word: 'car', letter: 'C', letters: 'C c', img: './assets/images/car.png',
      t: 47.125, beat: 46.31, echoStart: 48.16, echoEnd: 49.6 },
  ],
};

const CHANT_2 = {
  audio: './assets/units/2/chant.mp3',
  duration: 56.042,
  cues: [
    { word: 'duck', letter: 'D', letters: 'D d', img: './assets/units/2/words/duck.png',
      t: 9.042, beat: 7.88, echoStart: 9.91, echoEnd: 11.16 },
    { word: 'doll', letter: 'D', letters: 'D d', img: './assets/units/2/words/doll.png',
      t: 12.875, beat: 11.67, echoStart: 13.71, echoEnd: 15.17 },
    { word: 'door', letter: 'D', letters: 'D d', img: './assets/units/2/words/door.png',
      t: 16.625, beat: 15.52, echoStart: 17.54, echoEnd: 19.01 },
    { word: 'egg', letter: 'E', letters: 'E e', img: './assets/units/2/words/egg.png',
      t: 24.333, beat: 23.28, echoStart: 25.19, echoEnd: 26.55 },
    { word: 'elephant', letter: 'E', letters: 'E e', img: './assets/units/2/words/elephant.png',
      t: 28.125, beat: 27.08, echoStart: 29.025, echoEnd: 30.917 },
    { word: 'elbow', letter: 'E', letters: 'E e', img: './assets/units/2/words/elbow.png',
      t: 31.917, beat: 31.067, echoStart: 32.817, echoEnd: 35.017 },
    { word: 'fish', letter: 'F', letters: 'F f', img: './assets/units/2/words/fish.png',
      t: 39.542, beat: 38.5, echoStart: 40.4, echoEnd: 41.65 },
    { word: 'fork', letter: 'F', letters: 'F f', img: './assets/units/2/words/fork.png',
      t: 43.333, beat: 42.31, echoStart: 44.2, echoEnd: 45.57 },
    { word: 'frog', letter: 'F', letters: 'F f', img: './assets/units/2/words/frog.png',
      t: 47.167, beat: 46.12, echoStart: 48.03, echoEnd: 49.44 },
  ],
};

const CHANT_3 = {
  audio: './assets/units/3/chant.mp3',
  duration: 56.042,
  cues: [
    { word: 'girl', letter: 'G', letters: 'G g', img: './assets/units/3/words/girl.png',
      t: 9.042, beat: 8.12, echoStart: 10.14, echoEnd: 11.6 },
    { word: 'glove', letter: 'G', letters: 'G g', img: './assets/units/3/words/glove.png',
      t: 12.917, beat: 11.95, echoStart: 13.817, echoEnd: 15.57 },
    { word: 'green', letter: 'G', letters: 'G g', img: './assets/units/3/words/green.png',
      t: 16.708, beat: 15.72, echoStart: 17.608, echoEnd: 19.808 },
    { word: 'hand', letter: 'H', letters: 'H h', img: './assets/units/3/words/hand.png',
      t: 24.333, beat: 23.51, echoStart: 25.33, echoEnd: 26.86 },
    { word: 'hat', letter: 'H', letters: 'H h', img: './assets/units/3/words/hat.png',
      t: 28.083, beat: 27.27, echoStart: 29.15, echoEnd: 30.47 },
    { word: 'hippo', letter: 'H', letters: 'H h', img: './assets/units/3/words/hippo.png',
      t: 31.917, beat: 31.06, echoStart: 33.01, echoEnd: 34.65 },
    { word: 'ink', letter: 'I', letters: 'I i', img: './assets/units/3/words/ink.png',
      t: 39.542, beat: 38.71, echoStart: 40.61, echoEnd: 41.98 },
    { word: 'igloo', letter: 'I', letters: 'I i', img: './assets/units/3/words/igloo.png',
      t: 43.292, beat: 42.48, echoStart: 44.41, echoEnd: 46.61 },
    { word: 'Indian', letter: 'I', letters: 'I i', img: './assets/units/3/words/indian.png',
      t: 47.167, beat: 46.317, echoStart: 48.23, echoEnd: 49.91 },
  ],
};

const CHANT_4 = {
  audio: './assets/units/4/chant.mp3',
  duration: 56.042,
  cues: [
    { word: 'jet', letter: 'J', letters: 'J j', img: './assets/units/4/words/jet.png',
      t: 9.125, beat: 8.06, echoStart: 10.14, echoEnd: 11.38 },
    { word: 'jar', letter: 'J', letters: 'J j', img: './assets/units/4/words/jar.png',
      t: 12.958, beat: 11.86, echoStart: 13.858, echoEnd: 15.55 },
    { word: 'jacket', letter: 'J', letters: 'J j', img: './assets/units/4/words/jacket.png',
      t: 16.75, beat: 15.7, echoStart: 17.64, echoEnd: 19.25 },
    { word: 'key', letter: 'K', letters: 'K k', img: './assets/units/4/words/key.png',
      t: 24.375, beat: 23.49, echoStart: 25.32, echoEnd: 26.74 },
    { word: 'king', letter: 'K', letters: 'K k', img: './assets/units/4/words/king.png',
      t: 28.167, beat: 27.26, echoStart: 29.14, echoEnd: 29.54 },
    { word: 'kangaroo', letter: 'K', letters: 'K k', img: './assets/units/4/words/kangaroo.png',
      t: 32, beat: 31.58, echoStart: 32.9, echoEnd: 35.1 },
    { word: 'lion', letter: 'L', letters: 'L l', img: './assets/units/4/words/lion.png',
      t: 39.625, beat: 38.64, echoStart: 40.525, echoEnd: 42.22 },
    { word: 'lamp', letter: 'L', letters: 'L l', img: './assets/units/4/words/lamp.png',
      t: 43.417, beat: 42.37, echoStart: 44.18, echoEnd: 45.78 },
    { word: 'lemon', letter: 'L', letters: 'L l', img: './assets/units/4/words/lemon.png',
      t: 47.25, beat: 46.18, echoStart: 48.15, echoEnd: 49.1 },
  ],
};

const CHANT_5 = {
  audio: './assets/units/5/chant.mp3',
  duration: 56.042,
  cues: [
    { word: 'mom', letter: 'M', letters: 'M m', img: './assets/units/5/words/mom.png',
      t: 9.042, beat: 8.11, echoStart: 10.04, echoEnd: 11.47 },
    { word: 'milk', letter: 'M', letters: 'M m', img: './assets/units/5/words/milk.png',
      t: 12.875, beat: 11.92, echoStart: 13.82, echoEnd: 15.21 },
    { word: 'melon', letter: 'M', letters: 'M m', img: './assets/units/5/words/melon.png',
      t: 16.667, beat: 15.73, echoStart: 17.68, echoEnd: 19.24 },
    { word: 'nut', letter: 'N', letters: 'N n', img: './assets/units/5/words/nut.png',
      t: 24.292, beat: 23.39, echoStart: 25.29, echoEnd: 26.54 },
    { word: 'nail', letter: 'N', letters: 'N n', img: './assets/units/5/words/nail.png',
      t: 28.083, beat: 27.15, echoStart: 29.04, echoEnd: 30.61 },
    { word: 'neck', letter: 'N', letters: 'N n', img: './assets/units/5/words/neck.png',
      t: 31.917, beat: 30.97, echoStart: 32.88, echoEnd: 34.23 },
    { word: 'onion', letter: 'O', letters: 'O o', img: './assets/units/5/words/onion.png',
      t: 39.542, beat: 38.72, echoStart: 40.442, echoEnd: 42.35 },
    { word: 'ox', letter: 'O', letters: 'O o', img: './assets/units/5/words/ox.png',
      t: 43.333, beat: 42.5, echoStart: 44.38, echoEnd: 45.77 },
    { word: 'orange', letter: 'O', letters: 'O o', img: './assets/units/5/words/orange.png',
      t: 47.167, beat: 46.3, echoStart: 48.26, echoEnd: 49.71 },
  ],
};

const CHANT_6 = {
  audio: './assets/units/6/chant.mp3',
  duration: 55.958,
  cues: [
    { word: 'pig', letter: 'P', letters: 'P p', img: './assets/units/6/words/pig.png',
      t: 9.083, beat: 8.22, echoStart: 10.11, echoEnd: 11.42 },
    { word: 'pen', letter: 'P', letters: 'P p', img: './assets/units/6/words/pen.png',
      t: 12.917, beat: 11.99, echoStart: 13.85, echoEnd: 15.34 },
    { word: 'pear', letter: 'P', letters: 'P p', img: './assets/units/6/words/pear.png',
      t: 16.75, beat: 15.79, echoStart: 17.69, echoEnd: 19.12 },
    { word: 'queen', letter: 'Q', letters: 'Q q', img: './assets/units/6/words/queen.png',
      t: 24.333, beat: 23.44, echoStart: 25.33, echoEnd: 26.84 },
    { word: 'quilt', letter: 'Q', letters: 'Q q', img: './assets/units/6/words/quilt.png',
      t: 28.125, beat: 27.25, echoStart: 29.12, echoEnd: 30.43 },
    { word: 'quiet', letter: 'Q', letters: 'Q q', img: './assets/units/6/words/quiet.png',
      t: 31.958, beat: 31.55, echoStart: 32.94, echoEnd: 34.4 },
    { word: 'ring', letter: 'R', letters: 'R r', img: './assets/units/6/words/ring.png',
      t: 39.542, beat: 38.57, echoStart: 40.44, echoEnd: 42.06 },
    { word: 'red', letter: 'R', letters: 'R r', img: './assets/units/6/words/red.png',
      t: 43.375, beat: 42.35, echoStart: 44.22, echoEnd: 45.73 },
    { word: 'rabbit', letter: 'R', letters: 'R r', img: './assets/units/6/words/rabbit.png',
      t: 47.208, beat: 46.13, echoStart: 48.07, echoEnd: 49.62 },
  ],
};

const CHANT_7 = {
  audio: './assets/units/7/chant.mp3',
  duration: 48.542,
  cues: [
    { word: 'sun', letter: 'S', letters: 'S s', img: './assets/units/7/words/sun.png',
      t: 7.875, beat: 7.025, echoStart: 8.19, echoEnd: 9.71 },
    { word: 'sand', letter: 'S', letters: 'S s', img: './assets/units/7/words/sand.png',
      t: 11.208, beat: 10.06, echoStart: 11.98, echoEnd: 13.51 },
    { word: 'sock', letter: 'S', letters: 'S s', img: './assets/units/7/words/sock.png',
      t: 14.5, beat: 13.85, echoStart: 15.79, echoEnd: 17.13 },
    { word: 'sea', letter: 'S', letters: 'S s', img: './assets/units/7/words/sea.png',
      t: 21.083, beat: 19.59, echoStart: 21.46, echoEnd: 22.82 },
    { word: 'tent', letter: 'T', letters: 'T t', img: './assets/units/7/words/tent.png',
      t: 24.417, beat: 23.567, echoStart: 25.317, echoEnd: 27.06 },
    { word: 'toe', letter: 'T', letters: 'T t', img: './assets/units/7/words/toe.png',
      t: 27.708, beat: 27.21, echoStart: 29.06, echoEnd: 30.45 },
    { word: 'tiger', letter: 'T', letters: 'T t', img: './assets/units/7/words/tiger.png',
      t: 34.333, beat: 32.88, echoStart: 34.83, echoEnd: 36.4 },
    { word: 'turtle', letter: 'T', letters: 'T t', img: './assets/units/7/words/turtle.png',
      t: 37.625, beat: 36.72, echoStart: 38.64, echoEnd: 40.18 },
  ],
};

const CHANT_8 = {
  audio: './assets/units/8/chant.mp3',
  duration: 56.042,
  cues: [
    { word: 'uncle', letter: 'U', letters: 'U u', img: './assets/units/8/words/uncle.png',
      t: 9.125, beat: 8.18, echoStart: 10.13, echoEnd: 11.61 },
    { word: 'under', letter: 'U', letters: 'U u', img: './assets/units/8/words/under.png',
      t: 12.958, beat: 12.01, echoStart: 13.86, echoEnd: 15.4 },
    { word: 'umbrella', letter: 'U', letters: 'U u', img: './assets/units/8/words/umbrella.png',
      t: 16.75, beat: 15.81, echoStart: 17.72, echoEnd: 19.18 },
    { word: 'van', letter: 'V', letters: 'V v', img: './assets/units/8/words/van.png',
      t: 24.375, beat: 23.31, echoStart: 25.275, echoEnd: 27.167 },
    { word: 'vest', letter: 'V', letters: 'V v', img: './assets/units/8/words/vest.png',
      t: 28.167, beat: 27.317, echoStart: 28.97, echoEnd: 30.42 },
    { word: 'violin', letter: 'V', letters: 'V v', img: './assets/units/8/words/violin.png',
      t: 32, beat: 30.99, echoStart: 32.9, echoEnd: 35.1 },
    { word: 'watch', letter: 'W', letters: 'W w', img: './assets/units/8/words/watch.png',
      t: 39.625, beat: 38.6, echoStart: 40.46, echoEnd: 41.89 },
    { word: 'wand', letter: 'W', letters: 'W w', img: './assets/units/8/words/wand.png',
      t: 43.417, beat: 42.35, echoStart: 44.26, echoEnd: 46.46 },
    { word: 'window', letter: 'W', letters: 'W w', img: './assets/units/8/words/window.png',
      t: 47.25, beat: 46.4, echoStart: 48.15, echoEnd: 49.1 },
  ],
};

const CHANT_9 = {
  audio: './assets/units/9/chant.mp3',
  duration: 55.958,
  cues: [
    { word: 'ax', letter: 'X', letters: 'X x', img: './assets/units/9/words/ax.png',
      t: 9.125, beat: 7.78, echoStart: 9.2, echoEnd: 9.6 },
    { word: 'fox', letter: 'X', letters: 'X x', img: './assets/units/9/words/fox.png',
      t: 12.917, beat: 12.067, echoStart: 13.817, echoEnd: 15.708 },
    { word: 'X-ray', letter: 'X', letters: 'X x', img: './assets/units/9/words/x-ray.png',
      t: 16.708, beat: 15.858, echoStart: 17.608, echoEnd: 19.808 },
    { word: 'yak', letter: 'Y', letters: 'Y y', img: './assets/units/9/words/yak.png',
      t: 24.25, beat: 23.41, echoStart: 25.27, echoEnd: 26.63 },
    { word: 'yellow', letter: 'Y', letters: 'Y y', img: './assets/units/9/words/yellow.png',
      t: 28.042, beat: 27.17, echoStart: 28.942, echoEnd: 30.87 },
    { word: 'yo-yo', letter: 'Y', letters: 'Y y', img: './assets/units/9/words/yo-yo.png',
      t: 31.917, beat: 31.02, echoStart: 32.817, echoEnd: 35.017 },
    { word: 'zebra', letter: 'Z', letters: 'Z z', img: './assets/units/9/words/zebra.png',
      t: 39.5, beat: 38.6, echoStart: 40.4, echoEnd: 42.24 },
    { word: 'zero', letter: 'Z', letters: 'Z z', img: './assets/units/9/words/zero.png',
      t: 43.292, beat: 42.39, echoStart: 44.192, echoEnd: 46.083 },
    { word: 'zipper', letter: 'Z', letters: 'Z z', img: './assets/units/9/words/zipper.png',
      t: 47.083, beat: 46.233, echoStart: 48.11, echoEnd: 49.71 },
  ],
};

const STORY_1 = {
  scene: './assets/story/scene.jpg',
  audio: './assets/story/narration.mp3',
  canvas: [941, 1672],
  lead: 0.8,
  attractEnd: 8.71,
  end: 29.94,
  objects: [
    { key: 'cow', mode: 'cutout', cut: './assets/story/objects/cow.with.png', halo: './assets/story/objects/cow.with.halo.png',
      box: [152, 919, 197, 268], territory: [158, 925, 185, 256], song: true, role: 'carrier' },
    { key: 'alligator', mode: 'cutout', cut: './assets/story/objects/alligator.png', halo: './assets/story/objects/alligator.halo.png',
      box: [550, 1020, 285, 203], territory: [556, 1026, 273, 191], song: true, role: 'simple' },
    { key: 'bear', mode: 'cutout', cut: './assets/story/objects/bear.with.png', halo: './assets/story/objects/bear.with.halo.png',
      box: [384, 888, 188, 252], territory: [390, 894, 176, 240], song: true, role: 'carrier' },
    { key: 'ant', mode: 'cutout', cut: './assets/story/objects/ant.png', halo: './assets/story/objects/ant.halo.png',
      box: [256, 1159, 84, 103], territory: [262, 1165, 72, 91], song: true, role: 'simple' },
    { key: 'apple', mode: 'cutout', cut: './assets/story/objects/apple.png', halo: './assets/story/objects/apple.halo.png',
      box: [389, 958, 52, 50], territory: [395, 964, 40, 38], song: false, role: 'item' },
    { key: 'ball', mode: 'cutout', cut: './assets/story/objects/ball.png', halo: './assets/story/objects/ball.halo.png',
      box: [590, 1243, 108, 112], territory: [596, 1249, 96, 100], song: false, role: 'simple' },
    { key: 'cup', mode: 'cutout', cut: './assets/story/objects/cup.png', halo: './assets/story/objects/cup.halo.png',
      box: [282, 1025, 49, 59], territory: [288, 1031, 37, 47], song: false, role: 'item' },
    { key: 'car', mode: 'cutout', cut: './assets/story/objects/car.png', halo: './assets/story/objects/car.halo.png',
      box: [150, 771, 146, 113], territory: [156, 777, 134, 101], song: false, role: 'simple' },
    { key: 'bag', mode: 'cutout', cut: './assets/story/objects/bag.png', halo: './assets/story/objects/bag.halo.png',
      box: [717, 962, 120, 127], territory: [723, 968, 108, 115], song: false, role: 'simple' },
  ],
  beats: [
    { t: 9.39, key: 'cow', line: 'I see a cow', hl: 'cow' },
    { t: 11.53, key: 'alligator', line: 'I see an alligator', hl: 'alligator' },
    { t: 13.59, key: 'bear', line: 'I see a bear', hl: 'bear' },
    { t: 15.77, key: 'ant', line: 'I see an ant', hl: 'ant' },
    { t: 21.85, key: 'cow', line: 'I see a cow', hl: 'cow' },
    { t: 24, key: 'alligator', line: 'I see an alligator', hl: 'alligator' },
    { t: 26.02, key: 'bear', line: 'I see a bear', hl: 'bear' },
    { t: 28.14, key: 'ant', line: 'I see an ant', hl: 'ant' },
  ],
  lyrics: [
    { t: 8.49, text: 'I see a cow.', hl: 'cow' },
    { t: 10.63, text: 'I see an alligator.', hl: 'alligator' },
    { t: 12.69, text: 'I see a bear.', hl: 'bear' },
    { t: 14.87, text: 'I see an ant.', hl: 'ant' },
    { t: 20.95, text: 'I see a cow.', hl: 'cow' },
    { t: 23.1, text: 'I see an alligator.', hl: 'alligator' },
    { t: 25.12, text: 'I see a bear.', hl: 'bear' },
    { t: 27.24, text: 'I see an ant.', hl: 'ant' },
  ],
};

const STORY_2 = {
  scene: './assets/units/2/story/scene.jpg',
  audio: './assets/units/2/story/narration.mp3',
  canvas: [941, 1672],
  lead: 0.8,
  attractEnd: 8.22,
  end: 29.54,
  objects: [
    { key: 'doll', mode: 'cutout', cut: './assets/units/2/story/objects/doll.png', halo: './assets/units/2/story/objects/doll.halo.png',
      box: [569, 1014, 178, 196], territory: [575, 1020, 166, 184], song: false, role: 'simple' },
    { key: 'door', mode: 'cutout', cut: './assets/units/2/story/objects/door.png', halo: './assets/units/2/story/objects/door.halo.png',
      box: [552, 897, 123, 153], territory: [558, 903, 111, 141], song: false, role: 'simple' },
    { key: 'duck', mode: 'cutout', cut: './assets/units/2/story/objects/duck.with.png', halo: './assets/units/2/story/objects/duck.with.halo.png',
      box: [192, 951, 146, 214], territory: [198, 957, 112, 202], song: true, role: 'carrier' },
    { key: 'egg', mode: 'cutout', cut: './assets/units/2/story/objects/egg.png', halo: './assets/units/2/story/objects/egg.halo.png',
      box: [387, 1004, 64, 81], territory: [393, 1010, 52, 69], song: true, role: 'item' },
    { key: 'elephant', mode: 'cutout', cut: './assets/units/2/story/objects/elephant.with.png', halo: './assets/units/2/story/objects/elephant.with.halo.png',
      box: [313, 901, 192, 225], territory: [319, 907, 180, 213], song: true, role: 'carrier' },
    { key: 'fish', mode: 'cutout', cut: './assets/units/2/story/objects/fish.png', halo: './assets/units/2/story/objects/fish.halo.png',
      box: [287, 962, 51, 94], territory: [293, 968, 39, 82], song: true, role: 'item' },
    { key: 'frog', mode: 'cutout', cut: './assets/units/2/story/objects/frog.png', halo: './assets/units/2/story/objects/frog.halo.png',
      box: [471, 1027, 147, 133], territory: [477, 1033, 135, 121], song: true, role: 'simple' },
    { key: 'fork', mode: 'arrow', cut: '', halo: '',
      box: [499, 998, 52, 70], territory: [505, 1004, 40, 58], song: true, role: 'simple' },
  ],
  beats: [
    { t: 8.4, key: 'duck', line: 'The duck has a fish', hl: 'duck' },
    { t: 9.43, key: 'fish', line: 'The duck has a fish', hl: 'fish' },
    { t: 10.49, key: 'elephant', line: 'The elephant has an egg', hl: 'elephant' },
    { t: 11.59, key: 'egg', line: 'The elephant has an egg', hl: 'egg' },
    { t: 12.49, key: 'frog', line: 'The frog has a fork', hl: 'frog' },
    { t: 13.55, key: 'fork', line: 'The frog has a fork', hl: 'fork' },
    { t: 20.83, key: 'duck', line: 'The duck has a fish', hl: 'duck' },
    { t: 21.85, key: 'fish', line: 'The duck has a fish', hl: 'fish' },
    { t: 22.93, key: 'elephant', line: 'The elephant has an egg', hl: 'elephant' },
    { t: 24.01, key: 'egg', line: 'The elephant has an egg', hl: 'egg' },
    { t: 24.91, key: 'frog', line: 'The frog has a fork', hl: 'frog' },
    { t: 25.99, key: 'fork', line: 'The frog has a fork', hl: 'fork' },
  ],
  lyrics: [
    { t: 7.5, text: 'The duck has a fish.', hl: 'duck' },
    { t: 8.53, text: 'The duck has a fish.', hl: 'fish' },
    { t: 9.59, text: 'The elephant has an egg.', hl: 'elephant' },
    { t: 10.69, text: 'The elephant has an egg.', hl: 'egg' },
    { t: 11.59, text: 'The frog has a fork.', hl: 'frog' },
    { t: 12.65, text: 'The frog has a fork.', hl: 'fork' },
    { t: 15.1, text: 'Yum, yum, yum!', hl: 'None' },
    { t: 19.93, text: 'The duck has a fish.', hl: 'duck' },
    { t: 20.95, text: 'The duck has a fish.', hl: 'fish' },
    { t: 22.03, text: 'The elephant has an egg.', hl: 'elephant' },
    { t: 23.11, text: 'The elephant has an egg.', hl: 'egg' },
    { t: 24.01, text: 'The frog has a fork.', hl: 'frog' },
    { t: 25.09, text: 'The frog has a fork.', hl: 'fork' },
    { t: 27.5, text: 'Yum, yum, yum!', hl: 'None' },
  ],
};

const STORY_3 = {
  scene: './assets/units/3/story/scene.jpg',
  audio: './assets/units/3/story/narration.mp3',
  canvas: [941, 1672],
  lead: 0.8,
  attractEnd: 7.86,
  end: 31.27,
  objects: [
    { key: 'girl', mode: 'cutout', cut: './assets/units/3/story/objects/girl.png', halo: './assets/units/3/story/objects/girl.halo.png',
      box: [471, 912, 157, 253], territory: [477, 918, 145, 241], song: false, role: 'simple' },
    { key: 'glove', mode: 'cutout', cut: './assets/units/3/story/objects/glove.png', halo: './assets/units/3/story/objects/glove.halo.png',
      box: [465, 964, 42, 44], territory: [471, 970, 30, 32], song: false, role: 'simple' },
    { key: 'hand', mode: 'cutout', cut: './assets/units/3/story/objects/hand.png', halo: './assets/units/3/story/objects/hand.halo.png',
      box: [465, 964, 42, 44], territory: [471, 970, 30, 32], song: false, role: 'simple' },
    { key: 'hippo', mode: 'cutout', cut: './assets/units/3/story/objects/hippo.png', halo: './assets/units/3/story/objects/hippo.halo.png',
      box: [277, 887, 174, 267], territory: [283, 893, 162, 255], song: true, role: 'simple' },
    { key: 'igloo', mode: 'cutout', cut: './assets/units/3/story/objects/igloo.png', halo: './assets/units/3/story/objects/igloo.halo.png',
      box: [458, 841, 352, 266], territory: [464, 847, 340, 254], song: true, role: 'simple' },
    { key: 'hat', mode: 'cutout', cut: './assets/units/3/story/objects/hat.png', halo: './assets/units/3/story/objects/hat.halo.png',
      box: [391, 1128, 100, 85], territory: [397, 1134, 88, 73], song: true, role: 'simple' },
    { key: 'ink', mode: 'cutout', cut: './assets/units/3/story/objects/ink.png', halo: './assets/units/3/story/objects/ink.halo.png',
      box: [582, 1165, 82, 83], territory: [588, 1171, 70, 71], song: true, role: 'simple' },
  ],
  beats: [
    { t: 9.21, key: 'igloo', line: 'Welcome to my igloo', hl: 'igloo' },
    { t: 11.25, key: 'hippo', line: 'This is my hippo', hl: 'hippo' },
    { t: 13.35, key: 'ink', line: 'This is my ink', hl: 'ink' },
    { t: 15.63, key: 'hat', line: 'This is my green hat', hl: 'hat' },
    { t: 21.61, key: 'igloo', line: 'Welcome to my igloo', hl: 'igloo' },
    { t: 23.65, key: 'hippo', line: 'This is my hippo', hl: 'hippo' },
    { t: 25.75, key: 'ink', line: 'This is my ink', hl: 'ink' },
    { t: 28.07, key: 'hat', line: 'This is my green hat', hl: 'hat' },
  ],
  lyrics: [
    { t: 8.31, text: 'Welcome to my igloo.', hl: 'igloo' },
    { t: 10.35, text: 'This is my hippo.', hl: 'hippo' },
    { t: 12.45, text: 'This is my ink.', hl: 'ink' },
    { t: 14.73, text: 'This is my green hat.', hl: 'hat' },
    { t: 20.71, text: 'Welcome to my igloo.', hl: 'igloo' },
    { t: 22.75, text: 'This is my hippo.', hl: 'hippo' },
    { t: 24.85, text: 'This is my ink.', hl: 'ink' },
    { t: 27.17, text: 'This is my green hat.', hl: 'hat' },
  ],
};

const STORY_4 = {
  scene: './assets/units/4/story/scene.jpg',
  audio: './assets/units/4/story/narration.mp3',
  canvas: [941, 1672],
  lead: 0.8,
  attractEnd: 7.81,
  end: 30.47,
  objects: [
    { key: 'jacket', mode: 'cutout', cut: './assets/units/4/story/objects/jacket.png', halo: './assets/units/4/story/objects/jacket.halo.png',
      box: [266, 1197, 155, 109], territory: [272, 1203, 143, 97], song: true, role: 'simple' },
    { key: 'jar', mode: 'cutout', cut: './assets/units/4/story/objects/jar.png', halo: './assets/units/4/story/objects/jar.halo.png',
      box: [500, 1156, 81, 125], territory: [506, 1162, 69, 113], song: false, role: 'simple' },
    { key: 'kangaroo', mode: 'cutout', cut: './assets/units/4/story/objects/kangaroo.png', halo: './assets/units/4/story/objects/kangaroo.halo.png',
      box: [226, 894, 183, 283], territory: [232, 900, 171, 271], song: true, role: 'simple' },
    { key: 'key', mode: 'cutout', cut: './assets/units/4/story/objects/key.png', halo: './assets/units/4/story/objects/key.halo.png',
      box: [399, 1240, 103, 71], territory: [405, 1246, 91, 59], song: true, role: 'simple' },
    { key: 'lamp', mode: 'cutout', cut: './assets/units/4/story/objects/lamp.png', halo: './assets/units/4/story/objects/lamp.halo.png',
      box: [208, 1106, 82, 143], territory: [214, 1112, 70, 131], song: true, role: 'simple' },
    { key: 'lemon', mode: 'cutout', cut: './assets/units/4/story/objects/lemon.png', halo: './assets/units/4/story/objects/lemon.halo.png',
      box: [564, 1204, 90, 80], territory: [570, 1210, 78, 68], song: false, role: 'simple' },
    { key: 'lion', mode: 'cutout', cut: './assets/units/4/story/objects/lion.png', halo: './assets/units/4/story/objects/lion.halo.png',
      box: [409, 952, 150, 227], territory: [415, 958, 138, 215], song: false, role: 'simple' },
    { key: 'jet', mode: 'cutout', cut: './assets/units/4/story/objects/jet.png', halo: './assets/units/4/story/objects/jet.halo.png',
      box: [662, 1190, 122, 102], territory: [668, 1196, 110, 90], song: false, role: 'simple' },
  ],
  beats: [
    { t: 9.15, key: 'key', line: 'I like the key', hl: 'key' },
    { t: 11.21, key: 'lamp', line: 'I like the lamp', hl: 'lamp' },
    { t: 13.33, key: 'jacket', line: 'I like the jacket', hl: 'jacket' },
    { t: 14.87, key: 'kangaroo', line: 'I like kangaroos', hl: 'kangaroos' },
    { t: 21.59, key: 'key', line: 'I like the key', hl: 'key' },
    { t: 23.61, key: 'lamp', line: 'I like the lamp', hl: 'lamp' },
    { t: 25.73, key: 'jacket', line: 'I like the jacket', hl: 'jacket' },
    { t: 27.27, key: 'kangaroo', line: 'I like kangaroos', hl: 'kangaroos' },
  ],
  lyrics: [
    { t: 8.25, text: 'I like the key.', hl: 'key' },
    { t: 10.31, text: 'I like the lamp.', hl: 'lamp' },
    { t: 12.43, text: 'I like the jacket.', hl: 'jacket' },
    { t: 13.97, text: 'I like kangaroos.', hl: 'kangaroo' },
    { t: 20.69, text: 'I like the key.', hl: 'key' },
    { t: 22.71, text: 'I like the lamp.', hl: 'lamp' },
    { t: 24.83, text: 'I like the jacket.', hl: 'jacket' },
    { t: 26.37, text: 'I like kangaroos.', hl: 'kangaroo' },
  ],
};

const STORY_5 = {
  scene: './assets/units/5/story/scene.jpg',
  audio: './assets/units/5/story/narration.mp3',
  canvas: [941, 1672],
  lead: 0.8,
  attractEnd: 7.68,
  end: 31.52,
  objects: [
    { key: 'hen', mode: 'cutout', cut: './assets/units/5/story/objects/hen.png', halo: './assets/units/5/story/objects/hen.halo.png',
      box: [508, 914, 212, 248], territory: [514, 920, 200, 236], song: false, role: 'simple' },
    { key: 'melon', mode: 'cutout', cut: './assets/units/5/story/objects/melon.png', halo: './assets/units/5/story/objects/melon.halo.png',
      box: [329, 1130, 126, 91], territory: [335, 1136, 114, 79], song: false, role: 'simple' },
    { key: 'milk', mode: 'cutout', cut: './assets/units/5/story/objects/milk.png', halo: './assets/units/5/story/objects/milk.halo.png',
      box: [431, 1046, 71, 138], territory: [437, 1052, 59, 126], song: true, role: 'simple' },
    { key: 'nut', mode: 'cutout', cut: './assets/units/5/story/objects/nut.png', halo: './assets/units/5/story/objects/nut.halo.png',
      box: [470, 1137, 109, 90], territory: [476, 1143, 97, 78], song: true, role: 'simple' },
    { key: 'onion', mode: 'cutout', cut: './assets/units/5/story/objects/onion.png', halo: './assets/units/5/story/objects/onion.halo.png',
      box: [422, 1173, 74, 79], territory: [428, 1179, 62, 67], song: false, role: 'simple' },
    { key: 'orange', mode: 'cutout', cut: './assets/units/5/story/objects/orange.png', halo: './assets/units/5/story/objects/orange.halo.png',
      box: [568, 1131, 143, 114], territory: [574, 1137, 131, 102], song: true, role: 'simple' },
    { key: 'ox', mode: 'cutout', cut: './assets/units/5/story/objects/ox.png', halo: './assets/units/5/story/objects/ox.halo.png',
      box: [215, 899, 241, 266], territory: [221, 905, 229, 254], song: true, role: 'simple' },
  ],
  beats: [
    { t: 9.16, key: 'milk', line: 'Do you want some milk', hl: 'milk' },
    { t: 11.22, key: 'orange', line: 'Do you want some oranges', hl: 'oranges' },
    { t: 13.36, key: 'nut', line: 'Do you want some nuts', hl: 'nuts' },
    { t: 15.9, key: 'ox', line: 'No, I want an ox', hl: 'ox' },
    { t: 21.6, key: 'milk', line: 'Do you want some milk', hl: 'milk' },
    { t: 23.64, key: 'orange', line: 'Do you want some oranges', hl: 'oranges' },
    { t: 25.74, key: 'nut', line: 'Do you want some nuts', hl: 'nuts' },
    { t: 28.32, key: 'ox', line: 'No, I want an ox', hl: 'ox' },
  ],
  lyrics: [
    { t: 8.26, text: 'Do you want some milk?', hl: 'milk' },
    { t: 10.32, text: 'Do you want some oranges?', hl: 'orange' },
    { t: 12.46, text: 'Do you want some nuts?', hl: 'nut' },
    { t: 15, text: 'No, I want an ox!', hl: 'ox' },
    { t: 20.7, text: 'Do you want some milk?', hl: 'milk' },
    { t: 22.74, text: 'Do you want some oranges?', hl: 'orange' },
    { t: 24.84, text: 'Do you want some nuts?', hl: 'nut' },
    { t: 27.42, text: 'No, I want an ox!', hl: 'ox' },
  ],
};

const STORY_6 = {
  scene: './assets/units/6/story/scene.jpg',
  audio: './assets/units/6/story/narration.mp3',
  canvas: [941, 1672],
  lead: 0.8,
  attractEnd: 7.69,
  end: 30.81,
  objects: [
    { key: 'pear', mode: 'cutout', cut: './assets/units/6/story/objects/pear.png', halo: './assets/units/6/story/objects/pear.halo.png',
      box: [541, 1098, 76, 85], territory: [547, 1104, 64, 73], song: false, role: 'simple' },
    { key: 'pig', mode: 'cutout', cut: './assets/units/6/story/objects/pig.png', halo: './assets/units/6/story/objects/pig.halo.png',
      box: [233, 894, 148, 211], territory: [239, 900, 136, 199], song: false, role: 'simple' },
    { key: 'queen', mode: 'cutout', cut: './assets/units/6/story/objects/queen.png', halo: './assets/units/6/story/objects/queen.halo.png',
      box: [395, 819, 193, 297], territory: [401, 825, 181, 285], song: true, role: 'simple' },
    { key: 'rabbit', mode: 'cutout', cut: './assets/units/6/story/objects/rabbit.png', halo: './assets/units/6/story/objects/rabbit.halo.png',
      box: [571, 886, 129, 236], territory: [577, 892, 117, 224], song: false, role: 'simple' },
    { key: 'rose', mode: 'cutout', cut: './assets/units/6/story/objects/rose.png', halo: './assets/units/6/story/objects/rose.halo.png',
      box: [471, 1124, 70, 71], territory: [477, 1130, 58, 59], song: false, role: 'simple' },
    { key: 'quilt', mode: 'cutout', cut: './assets/units/6/story/objects/quilt.png', halo: './assets/units/6/story/objects/quilt.halo.png',
      box: [294, 1069, 192, 129], territory: [300, 1075, 180, 117], song: true, role: 'simple' },
    { key: 'ring', mode: 'arrow', cut: '', halo: '',
      box: [394, 946, 42, 46], territory: [400, 952, 30, 34], song: true, role: 'simple' },
    { key: 'pen', mode: 'cutout', cut: './assets/units/6/story/objects/pen.png', halo: './assets/units/6/story/objects/pen.halo.png',
      box: [585, 1109, 164, 101], territory: [591, 1115, 152, 89], song: false, role: 'simple' },
  ],
  beats: [
    { t: 9.13, key: 'quilt', line: 'Look at the quilt', hl: 'quilt' },
    { t: 11.23, key: 'ring', line: 'Look at the ring', hl: 'ring' },
    { t: 13.29, key: 'queen', line: 'Look at the queen', hl: 'queen' },
    { t: 15.13, key: 'queen', line: 'Look at the queen', hl: 'queen' },
    { t: 21.57, key: 'queen', line: 'Look at the queen', hl: 'queen' },
    { t: 22.21, key: 'quilt', line: 'Look at the quilt', hl: 'quilt' },
    { t: 23.67, key: 'ring', line: 'Look at the ring', hl: 'ring' },
    { t: 25.67, key: 'queen', line: 'Look at the queen', hl: 'queen' },
    { t: 27.61, key: 'queen', line: 'Look at the queen', hl: 'queen' },
  ],
  lyrics: [
    { t: 8.23, text: 'Look at the quilt.', hl: 'quilt' },
    { t: 10.33, text: 'Look at the ring.', hl: 'ring' },
    { t: 12.39, text: 'Look at the queen.', hl: 'queen' },
    { t: 14.23, text: 'What a pretty queen!', hl: 'queen' },
    { t: 20.67, text: 'Look at the queen.', hl: 'queen' },
    { t: 21.31, text: 'Look at the quilt.', hl: 'quilt' },
    { t: 22.77, text: 'Look at the ring.', hl: 'ring' },
    { t: 24.77, text: 'Look at the queen.', hl: 'queen' },
    { t: 26.71, text: 'What a pretty queen!', hl: 'queen' },
  ],
};

const STORY_7 = {
  scene: './assets/units/7/story/scene.jpg',
  audio: './assets/units/7/story/narration.mp3',
  canvas: [941, 1672],
  lead: 0.8,
  attractEnd: 7.71,
  end: 30.75,
  objects: [
    { key: 'sock', mode: 'cutout', cut: './assets/units/7/story/objects/sock.png', halo: './assets/units/7/story/objects/sock.halo.png',
      box: [500, 1141, 151, 108], territory: [506, 1147, 139, 96], song: true, role: 'simple' },
    { key: 'sun', mode: 'cutout', cut: './assets/units/7/story/objects/sun.png', halo: './assets/units/7/story/objects/sun.halo.png',
      box: [637, 499, 96, 98], territory: [643, 505, 84, 86], song: false, role: 'simple' },
    { key: 'tent', mode: 'cutout', cut: './assets/units/7/story/objects/tent.png', halo: './assets/units/7/story/objects/tent.halo.png',
      box: [400, 767, 253, 327], territory: [406, 773, 241, 315], song: true, role: 'simple' },
    { key: 'tiger', mode: 'cutout', cut: './assets/units/7/story/objects/tiger.png', halo: './assets/units/7/story/objects/tiger.halo.png',
      box: [207, 887, 193, 246], territory: [213, 893, 181, 234], song: false, role: 'simple' },
    { key: 'turtle', mode: 'cutout', cut: './assets/units/7/story/objects/turtle.png', halo: './assets/units/7/story/objects/turtle.halo.png',
      box: [282, 1042, 221, 146], territory: [288, 1048, 209, 134], song: false, role: 'simple' },
    { key: 'toe', mode: 'arrow', cut: '', halo: '',
      box: [586, 1074, 48, 40], territory: [592, 1080, 36, 28], song: true, role: 'simple' },
  ],
  beats: [
    { t: 9.17, key: 'tent', line: 'There is a tent', hl: 'tent' },
    { t: 11.23, key: 'sock', line: 'There is a sock', hl: 'sock' },
    { t: 13.29, key: 'toe', line: 'There is a toe', hl: 'toe' },
    { t: 15.21, key: 'toe', line: 'There is a toe', hl: 'toe' },
    { t: 21.63, key: 'toe', line: 'There is a toe', hl: 'toe' },
    { t: 22.07, key: 'tent', line: 'There is a tent', hl: 'tent' },
    { t: 23.71, key: 'sock', line: 'There is a sock', hl: 'sock' },
    { t: 25.77, key: 'toe', line: 'There is a toe', hl: 'toe' },
    { t: 27.55, key: 'toe', line: 'There is a toe', hl: 'toe' },
  ],
  lyrics: [
    { t: 8.27, text: 'There is a tent.', hl: 'tent' },
    { t: 10.33, text: 'There is a sock.', hl: 'sock' },
    { t: 12.39, text: 'There is a toe.', hl: 'toe' },
    { t: 14.31, text: 'What a big toe!', hl: 'toe' },
    { t: 20.73, text: 'There is a toe.', hl: 'toe' },
    { t: 21.17, text: 'There is a tent.', hl: 'tent' },
    { t: 22.81, text: 'There is a sock.', hl: 'sock' },
    { t: 24.87, text: 'There is a toe.', hl: 'toe' },
    { t: 26.65, text: 'What a big toe!', hl: 'toe' },
  ],
};

const STORY_8 = {
  scene: './assets/units/8/story/scene.jpg',
  audio: './assets/units/8/story/narration.mp3',
  canvas: [941, 1672],
  lead: 0.8,
  attractEnd: 6.86,
  end: 46.52,
  objects: [
    { key: 'umbrella', mode: 'cutout', cut: './assets/units/8/story/objects/umbrella.png', halo: './assets/units/8/story/objects/umbrella.halo.png',
      box: [306, 757, 245, 202], territory: [312, 763, 233, 190], song: true, role: 'simple' },
    { key: 'uncle', mode: 'cutout', cut: './assets/units/8/story/objects/uncle.with.png', halo: './assets/units/8/story/objects/uncle.with.halo.png',
      box: [380, 841, 171, 322], territory: [386, 847, 159, 310], song: false, role: 'carrier' },
    { key: 'van', mode: 'cutout', cut: './assets/units/8/story/objects/van.png', halo: './assets/units/8/story/objects/van.halo.png',
      box: [154, 969, 226, 202], territory: [160, 975, 214, 190], song: false, role: 'simple' },
    { key: 'vest', mode: 'cutout', cut: './assets/units/8/story/objects/vest.png', halo: './assets/units/8/story/objects/vest.halo.png',
      box: [414, 948, 103, 113], territory: [420, 954, 91, 101], song: false, role: 'item' },
    { key: 'violin', mode: 'cutout', cut: './assets/units/8/story/objects/violin.png', halo: './assets/units/8/story/objects/violin.halo.png',
      box: [444, 1109, 150, 172], territory: [450, 1115, 138, 160], song: true, role: 'simple' },
    { key: 'wand', mode: 'cutout', cut: './assets/units/8/story/objects/wand.png', halo: './assets/units/8/story/objects/wand.halo.png',
      box: [563, 1133, 117, 150], territory: [569, 1139, 105, 138], song: true, role: 'simple' },
    { key: 'watch', mode: 'cutout', cut: './assets/units/8/story/objects/watch.png', halo: './assets/units/8/story/objects/watch.halo.png',
      box: [311, 1108, 113, 158], territory: [317, 1114, 101, 146], song: true, role: 'simple' },
    { key: 'window', mode: 'cutout', cut: './assets/units/8/story/objects/window.png', halo: './assets/units/8/story/objects/window.halo.png',
      box: [577, 829, 70, 75], territory: [583, 835, 58, 63], song: false, role: 'simple' },
  ],
  beats: [
    { t: 10.2, key: 'umbrella', line: 'Do you have an umbrella', hl: 'umbrella' },
    { t: 14.32, key: 'wand', line: 'Do you have a wand', hl: 'wand' },
    { t: 19.12, key: 'violin', line: 'Do you have a violin', hl: 'violin' },
    { t: 22.66, key: 'watch', line: 'Yes, I have a watch too', hl: 'watch' },
    { t: 30.9, key: 'umbrella', line: 'Do you have an umbrella', hl: 'umbrella' },
    { t: 35.02, key: 'wand', line: 'Do you have a wand', hl: 'wand' },
    { t: 40.04, key: 'violin', line: 'Do you have a violin', hl: 'violin' },
    { t: 43.32, key: 'watch', line: 'Yes, I have a watch too', hl: 'watch' },
  ],
  lyrics: [
    { t: 9.3, text: 'Do you have an umbrella?', hl: 'umbrella' },
    { t: 13.42, text: 'Do you have a wand?', hl: 'wand' },
    { t: 18.22, text: 'Do you have a violin?', hl: 'violin' },
    { t: 21.76, text: 'Yes, I have a watch too!', hl: 'watch' },
    { t: 30, text: 'Do you have an umbrella?', hl: 'umbrella' },
    { t: 34.12, text: 'Do you have a wand?', hl: 'wand' },
    { t: 39.14, text: 'Do you have a violin?', hl: 'violin' },
    { t: 42.42, text: 'Yes, I have a watch too!', hl: 'watch' },
  ],
};

const STORY_9 = {
  scene: './assets/units/9/story/scene.jpg',
  audio: './assets/units/9/story/narration.mp3',
  canvas: [941, 1672],
  lead: 0.8,
  attractEnd: 7.86,
  end: 31.02,
  objects: [
    { key: 'yak', mode: 'cutout', cut: './assets/units/9/story/objects/yak.png', halo: './assets/units/9/story/objects/yak.halo.png',
      box: [60, 858, 267, 317], territory: [66, 864, 255, 305], song: true, role: 'simple' },
    { key: 'fox', mode: 'cutout', cut: './assets/units/9/story/objects/fox.png', halo: './assets/units/9/story/objects/fox.halo.png',
      box: [312, 848, 165, 271], territory: [318, 854, 153, 259], song: true, role: 'simple' },
    { key: 'zebra', mode: 'cutout', cut: './assets/units/9/story/objects/zebra.png', halo: './assets/units/9/story/objects/zebra.halo.png',
      box: [550, 815, 171, 309], territory: [556, 821, 159, 297], song: true, role: 'simple' },
    { key: 'x-ray', mode: 'cutout', cut: './assets/units/9/story/objects/x-ray.png', halo: './assets/units/9/story/objects/x-ray.halo.png',
      box: [365, 715, 282, 263], territory: [371, 721, 270, 251], song: true, role: 'simple' },
    { key: 'flower', mode: 'cutout', cut: './assets/units/9/story/objects/flower.png', halo: './assets/units/9/story/objects/flower.halo.png',
      box: [286, 1348, 78, 66], territory: [292, 1354, 66, 54], song: false, role: 'simple' },
    { key: 'axe', mode: 'cutout', cut: './assets/units/9/story/objects/axe.png', halo: './assets/units/9/story/objects/axe.halo.png',
      box: [513, 1155, 177, 124], territory: [519, 1161, 165, 112], song: false, role: 'simple' },
    { key: 'zipper', mode: 'cutout', cut: './assets/units/9/story/objects/zipper.png', halo: './assets/units/9/story/objects/zipper.halo.png',
      box: [715, 1053, 119, 145], territory: [721, 1059, 107, 133], song: false, role: 'simple' },
    { key: 'yo-yo', mode: 'cutout', cut: './assets/units/9/story/objects/yo-yo.png', halo: './assets/units/9/story/objects/yo-yo.halo.png',
      box: [265, 1172, 158, 112], territory: [271, 1178, 146, 100], song: false, role: 'simple' },
  ],
  beats: [
    { t: 9.5, key: 'x-ray', line: 'None', hl: 'None' },
    { t: 11.1, key: 'yak', line: 'Is it a yak', hl: 'yak' },
    { t: 13.1, key: 'fox', line: 'Is it a fox', hl: 'fox' },
    { t: 15.4, key: 'zebra', line: 'No, it\'s a zebra', hl: 'zebra' },
    { t: 21.7, key: 'x-ray', line: 'None', hl: 'None' },
    { t: 23.3, key: 'yak', line: 'Is it a yak', hl: 'yak' },
    { t: 25.5, key: 'fox', line: 'Is it a fox', hl: 'fox' },
    { t: 27.8, key: 'zebra', line: 'No, it\'s a zebra', hl: 'zebra' },
  ],
  lyrics: [
    { t: 8.6, text: 'Whose X-ray is it?', hl: 'x-ray' },
    { t: 10.2, text: 'Is it a yak?', hl: 'yak' },
    { t: 12.2, text: 'Is it a fox?', hl: 'fox' },
    { t: 14.5, text: 'No, it\'s a zebra!', hl: 'zebra' },
    { t: 20.8, text: 'Whose X-ray is it?', hl: 'x-ray' },
    { t: 22.4, text: 'Is it a yak?', hl: 'yak' },
    { t: 24.6, text: 'Is it a fox?', hl: 'fox' },
    { t: 26.9, text: 'No, it\'s a zebra!', hl: 'zebra' },
  ],
};

const LETTER_UNITS = [
  { n: 1, face: '🍎', letters: ['A', 'B', 'C'], words: UNIT1, chant: CHANT_1, story: STORY_1 },
  { n: 2, face: '🐘', letters: ['D', 'E', 'F'], words: WORDS_2, chant: CHANT_2, story: STORY_2 },
  { n: 3, face: '🦛', letters: ['G', 'H', 'I'], words: WORDS_3, chant: CHANT_3, story: STORY_3 },
  { n: 4, face: '🦘', letters: ['J', 'K', 'L'], words: WORDS_4, chant: CHANT_4, story: STORY_4 },
  { n: 5, face: '🍊', letters: ['M', 'N', 'O'], words: WORDS_5, chant: CHANT_5, story: STORY_5 },
  { n: 6, face: '👑', letters: ['P', 'Q', 'R'], words: WORDS_6, chant: CHANT_6, story: STORY_6 },
  { n: 7, face: '🐯', letters: ['S', 'T'], words: WORDS_7, chant: CHANT_7, story: STORY_7 },
  { n: 8, face: '☂️', letters: ['U', 'V', 'W'], words: WORDS_8, chant: CHANT_8, story: STORY_8 },
  { n: 9, face: '🦓', letters: ['X', 'Y', 'Z'], words: WORDS_9, chant: CHANT_9, story: STORY_9 },
];

export const UNITS = [
  ...LETTER_UNITS.map((unit) => ({
    n: unit.n,
    label: unit.letters.map((l) => l + l.toLowerCase()).join(' '),
    chips: unit.letters.map((l) => l + l.toLowerCase()),
    face: unit.face,
    state: unit.n === 1 ? 'current' : 'open',
    letters: unit.letters,
    words: unit.words,
    chant: unit.chant,
    story: unit.story,
    steps: letterSteps(unit.face),
    preload: [
      ...unit.words.map((word) => word.utter),
      unit.chant.audio,
      ...unit.letters.map((letter) => VOICE + 'pop-the-' + letter.toLowerCase() + '.mp3'),
      ...LETTER_SFX,
    ],
  })),
  {
    n: 10,
    title: 'Digits',
    label: 'Digits',
    chips: ['1 2 3', '4 5 6', '7 8 9 0'],
    face: '🔢',
    state: 'open',
    steps: [
      { id: 'numbers', icon: '🔢', tone: 'primary' },
      { id: 'count', icon: '👆', tone: 'success' },
      { id: 'howmany', icon: '❓', tone: 'reward' },
      { id: 'addup', icon: '➕', tone: 'celebration' },
      { id: 'matchup', icon: '🔎', tone: 'grape' },
    ],
    preload: [
      ...DIGITS.map((d) => d.clip),
      ...DIGITS.map((d) => `${U2}num-${d.digit}.mp3`),
      ...COUNT_TOTALS.map((d) => `${U2}total-${d}.mp3`),
      ...MATH_PROBLEMS.map((p) => p.clip),
      U2 + 'count-with-me.mp3',
      U2 + 'how-many.mp3',
      U2 + 'lets-add.mp3',
      U2 + 'find-the-number.mp3',
      U2 + 'find-that-many.mp3',
      U2 + 'nice-counting.mp3',
      U2 + 'you-know-your-numbers.mp3',
      SFX + 'correct.mp3',
      SFX + 'wrong.mp3',
      SFX + 'pop.mp3',
      SFX + 'stage-clear.mp3',
    ],
  },
];

export function findUnit(n) {
  return UNITS.find((u) => u.n === n);
}
